[project]
name = "pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "openai>=2.2.0",
    "openai-rust-client",
    "psutil>=7.1.1",
]

[tool.uv.sources]
openai-rust-client = { workspace = true }
